### ISSUE TITLE
Add open files metrics

### ISSUE THREAD

**Issue by francisdb** [kamon-io/kamon-system-metrics#12]
You can get these from the `OperatingSystem` mbean

`MaxFileDescriptorCount`
`OpenFileDescriptorCount`

**Comment by dpsoft** [comment]
@francisdb currently we are extracting this metric from Sigar: https://github.com/kamon-io/kamon-system-metrics/blob/master/src/main/scala/kamon/system/process/ULimitMetrics.scala

**Comment by francisdb** [comment]
Aha, looks like I missed that part

**Comment by francisdb** [comment]
see  #13
