### ISSUE TITLE
Please upgrade sigar-loader to suppress the Exception on JDK10+

### ISSUE THREAD

**Issue by sebtomba** [kamon-io/kamon-system-metrics#17]
The current version of `kamon-system-metrics` has the issue described in https://github.com/kamon-io/sigar-loader/issues/9

It has been fixed in PR https://github.com/kamon-io/sigar-loader/pull/10
However, I'm afraid that the version of `sigar-loader` hasn't been bumped.

Please upgrade `kamon-system-metrics` to include the bugfix.

Thanks!

**Comment by dpsoft** [comment]
@sebtomba done: https://bintray.com/kamon-io/releases/kamon-system-metrics/1.0.1
