### ISSUE TITLE
process.cpu > 100 

### ISSUE THREAD

**Issue by frubby** [kamon-io/kamon-system-metrics#19]
i use kamon to monitor spring application , I found just once process.cpu is higher than 100 (3 services, two service's process is someting wrong,because at the same time the server cpu is just under 30%).

![11_29_46__01_18_2019](https://user-images.githubusercontent.com/5885426/51363868-e3673b00-1b14-11e9-9ae4-645e487a6aae.jpg)
![11_30_01__01_18_2019](https://user-images.githubusercontent.com/5885426/51363869-e7935880-1b14-11e9-9e7a-0537b5aa63bd.jpg)

kamon-core 1.1.2
kamon-system 1.0.0

**Comment by ivantopo** [comment]
I'm almost sure that this had to do with wrong calculation of CPU usage on multi-core machines and this has already been fixed on Kamon 2.0 series. Going to close this one but please, feel free to report back if you see this happen again in 2.x!
