### ISSUE TITLE
JVM threads metrics are missing

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/kamon-system-metrics#25]
We no longer have the JVM Thread metrics as we had them in 1.x here: https://github.com/kamon-io/kamon-system-metrics/blob/v1.0.1/src/main/scala/kamon/system/jvm/ThreadsMetrics.scala

**Comment by danischroeter** [comment]
jep - also run into this. Would be helpful and probably easy to fix.
Having all dispatchers of an akka system monitored automatically is already a nice addition in 2.0 but does not show the whole picture...

**Comment by danbim** [comment]
+1 :)

**Comment by danischroeter** [comment]
Hmm @ivantopo have the ThreadMetrics been removed because you wanted to get the data from oshi instead of jmx or was this just an accident?

**Comment by ivantopo** [comment]
Hey @danischroeter, nope. I guess I just missed them during the upgrade to 2.0. I'm going to put them back in now.
