### ISSUE TITLE
Typo in reference.conf

### ISSUE THREAD

**Issue by vkrot** [kamon-io/kamon-system-metrics#6]
There is a typo in reference.conf on line 38, I believe "metrics.instrument-settings" should be "metric.instrument-settings" (no plural form in `metric`). As a result all default settings are lost and instrument settings set to default.
I tried to fix this, but after the fix tests start failing - jvm just crashes, so I don't attach a PR.

Moreover, due to this typo, it is hard for users to change any of these settings. Default hrd highest trackable value is too low for global context switch values, when changing it took a while to figure out this typo and realize what key for histogram settings should I use.

**Comment by ivantopo** [comment]
Hello there! I'm sorry for not checking this out before. At this point this is no longer an issue in Kamon 2.x series so I'm going to close this. If you find any issues in the new version please let us know!
